import pandas as pd
import numpy as np


def compute_repeat_and_SNP_density(bedfile, SNPwinsize):
    """
    Function takes in a file generated by using bedtools intersect -wao -a windowed_branch_lengths -b ucsc_repeat_masker
    and computes the repeat density by dividing the total repeat length in that window by the window size
    
    :param bedfile: filename generated by bedtools intersect
    :type bedfile: str
    :return: table with the per window branch length and repeat density
    :rtype: DataFrame
    """

    #opening intersect file
    df = pd.read_csv(
        bedfile,
        sep="\t", header=None,
        names=["CHROM","START","END","Avg_Branch_Length","uscschrom","uscsstart","uscsend","overlap_bp"]
        )
    
    #dropping unnecessary columns
    df.drop(["uscschrom","uscsstart","uscsend"], axis=1, inplace=True)

    #summing repeat lengths for windows with multiple repeats
    summed_df = df.groupby(["CHROM", "START", "END", "Avg_Branch_Length"], as_index=False, sort=False)["overlap_bp"].sum()

    #compute densities
    summed_df["Repeat_Density"] = summed_df["overlap_bp"] / (summed_df["END"] - summed_df["START"])
    summed_df["SNP_Density"] = SNPwinsize / (summed_df["END"] - summed_df["START"])


    #remove unnecessary column
    summed_df.drop("overlap_bp", axis=1, inplace=True)


    return summed_df



def remove_bad_regions(df, region_list):
    """
    Function takes in the DataFrame generated from compute_repeat_and_SNP_density and removes specified regions.
    This is used to remove centromeric regions that skew the branch lengths.
    
    :param df: DataFrame from compute_repeat_and_SNP_density
    :type df: DataFrame
    :param region_list: List of tuples each containing 3 elements: "chrom", start_site, end_site
    :type region_list: List of Tuples

    :return: DataFrame with removed regions
    :rtype: DataFrame
    """

    #setting empty mask
    keep_rows = np.ones(len(df), dtype=bool)

    #masking rows for windows entirely or partially overlapping with regions to remove
    for chrom, region_start, region_end in region_list:
        keep_rows &= ~((df["CHROM"] == chrom) & (df["START"] < region_end) & (df["END"] > region_start))

    #removing bad rows
    df = df[keep_rows]


    return df




def main(bedfile, snpwinsize, remove_regions, outfile):
    """
    Main function that runs compute_repeat_and_SNP_density and remove_bad_regions and outputs a TSV file
    
    :param bedfile: bedfile name
    :type bedfile: str
    :param remove_regions: list of tuples with regions to remove
    :type remove_regions: List of Tuples
    :param outfile: name of output TSV
    :type outfile: str

    :return: None
    """

    den_df = compute_repeat_and_SNP_density(bedfile, snpwinsize)
    cleaned_df = remove_bad_regions(den_df, remove_regions)

    cleaned_df.to_csv(f"{outfile}.tsv", sep="\t", index=False)



### REGIONS TO REMOVE ###
remove_these = [
    ("chr1", 122026460-3500000, 125184587+3500000), ("chr2", 92188146-3500000, 94090557+3500000), ("chr3", 90772459-3500000, 93655574+3500000), ("chr4", 49708101-3500000, 51743951+3500000), ("chr5", 46485901-3500000, 50059807+3500000),
    ("chr6", 58553889-3500000, 59829934+3500000), ("chr7", 58169654-3500000, 60828234+3500000), ("chr8", 44033745-3500000, 45877265+3500000), ("chr9", 43236168-3500000, 45518558+3500000), ("chr10", 39686683-3500000, 41593521+3500000),
    ("chr11", 51078349-3500000, 54425074+3500000), ("chr12", 34769408-3500000, 37185252+3500000), ("chr13", 16000001-3500000, 18051248+3500000), ("chr14", 16000001-3500000, 18173523+3500000), ("chr15", 17000001-3500000, 19725254+3500000),
    ("chr16", 36311159-3500000, 38280682+3500000), ("chr17", 22813680-3500000, 26885980+3500000), ("chr18", 15460900-3500000, 20861206+3500000), ("chr19", 24498981-3500000, 27190874+3500000), ("chr20", 26436233-3500000, 30038348+3500000),
    ("chr21", 10864561-3500000, 12915808+3500000), ("chr22", 12954789-3500000, 15054318+3500000), ("chrX", 58605580-3500000, 62412542+3500000), ("chrY", 10316945-3500000, 10544039+3500000), ("chrY", 26557757, 57227415)
]


main("window_repeat_overlaps.bed", 100, remove_these, "cleaned_windowed_AvgBranchLen_RepeatDen_SNPden")